characters = {  
    sol: {
        name: "Sol Badguy",
        image: "https://www.dustloop.com/wiki/images/7/75/GGST_Sol_Badguy_Icon.png",
        playstyle: "prepared",
        moral_system: "grey",
        gender: "male",
        favourite: ["pressure"],
        important: ["all_rounder", "damage"],
        zoning: 0.0,
        rushdown: 1.0,
        oneplayer: "sometimes",
        range: ["close", "mid"],
        stance: "no",
        charge: "no",
        gameplan: ["risc", "frametrap"],
        setplay: "neutral",
        projectile: "limited",
        reversal: ["meterless", "metered"],
        resource: "no",
        vortex: "neutral",
        score: 0
    },
    ky: {
        name: "Ky Kiske",
        image: "https://www.dustloop.com/wiki/images/d/d8/GGST_Ky_Kiske_Icon.png",
        playstyle: "prepared",
        moral_system: "good",
        gender: "male",
        favourite: ["neutral", "pressure"],
        important: ["all_rounder"],
        zoning: 0.5,
        rushdown: 0.5,
        oneplayer: "no",
        range: ["mid", "all"],
        stance: "no",
        charge: "no",
        gameplan: ["frametrap"],
        setplay: "oki",
        projectile: ["standard", "special"],
        reversal: ["meterless", "metered"],
        resource: "no",
        vortex: "projectile",
        score: 0
    },
    May: {
        name: "May",
        image: "https://www.dustloop.com/wiki/images/5/51/GGST_May_Icon.png",
        playstyle: "rewarding",
        moral_system: "good",
        gender: "female",
        favourite: ["neutral", "combos"],
        important: ["mobility", "damage"],
        zoning: 0.25,
        rushdown: 0.75,
        oneplayer: "no",
        range: "mid",
        stance: "no",
        charge: "yes",
        gameplan: ["grab", "highlow"],
        setplay: ["neutral", "oki"],
        projectile: ["limited", "special"],
        reversal: "metered",
        resource: "no",
        vortex: "projectile",
        score: 0
    },
    faust: {
        name: "Faust",
        image: "https://www.dustloop.com/wiki/images/f/f7/GGST_Faust_Icon.png",
        playstyle: "specialist",
        moral_system: "neutral",
        gender: "male",
        favourite: ["neutral"],
        important: ["utility"],
        zoning: 1.0,
        rushdown: 0.0,
        oneplayer: "no",
        range: "long",
        stance: "no",
        charge: "no",
        gameplan: ["grab", "highlow"],
        setplay: ["no"],
        projectile: ["limited","special"],
        reversal: "metered",
        resource: "no",
        vortex: "projectile",
        score: 0
    },
    millia: {
        name: "Millia Rage",
        image: "https://www.dustloop.com/wiki/images/d/d8/GGST_Millia_Rage_Icon.png",
        playstyle: "specialist",
        moral_system: "grey",
        gender: "female",
        favourite: ["mindgames", "neutral"],
        important: ["mobility", "utility"],
        zoning: 0.0,
        rushdown: 1.0,
        oneplayer: "yes",
        range: ["close", "mid"],
        stance: "no",
        charge: "no",
        gameplan: ["highlow", "leftright"],
        setplay: ["oki"],
        projectile: "special",
        reversal: "metered",
        resource: "no",
        vortex: "lots",
        score: 0
    },
    chipp: {
        name: "Chipp Zanuff",
        image: "https://www.dustloop.com/wiki/images/9/94/GGST_Chipp_Zanuff_Icon.png",
        playstyle: "prepared",
        moral_system: "good",
        gender: "male",
        favourite: ["pressure", "neutral"],
        important: ["mobility", "utility"],
        zoning: 0.0,
        rushdown: 1.0,
        oneplayer: "sometimes",
        range: "close",
        stance: "no",
        charge: "no",
        gameplan: ["highlow", "leftright"],
        setplay: ["no"],
        projectile: "limited",
        reversal: ["meterless", "metered"],
        resource: "no",
        vortex: "lots",
        score: 0
    },
    ino: {
        name: "I-No",
        image: "https://www.dustloop.com/wiki/images/9/94/GGST_I-No_Icon.png",
        playstyle: "rewarding",
        moral_system: "evil",
        gender: "female",
        favourite: ["mindgames"],
        important: ["mobility"],
        zoning: 0.0,
        rushdown: 1.0,
        oneplayer: "yes",
        range: "close",
        stance: "no",
        charge: "no",
        gameplan: ["highlow"],
        setplay: ["neutral"],
        projectile: "standard",
        reversal: "metered",
        resource: "no",
        vortex: "lots",
        score: 0
    },
    axl: {
        name: "Axl Low",
        image: "https://www.dustloop.com/wiki/images/b/b6/GGST_Axl_Low_Icon.png",
        playstyle: "specialist",
        moral_system: "neutral",
        gender: "male",
        favourite: ["neutral", "pressure"],
        important: ["all_rounder"],
        zoning: 1.0,
        rushdown: 0.0,
        oneplayer: "no",
        range: ["mid", "long"],
        stance: "yes",
        charge: ["sometimes", "yes"],
        gameplan: ["frametrap", "risc"],
        setplay: ["neutral"],
        projectile: "no",
        reversal: ["meterless", "metered"],
        resource: "no",
        vortex: "neutral",
        score: 0
    },
    zato: {
        name: "Zato-1",
        image: "https://www.dustloop.com/wiki/images/5/51/GGST_Zato-1_Icon.png",
        playstyle: "rewarding",
        moral_system: "neutral",
        gender: "male",
        favourite: ["combos", "mindgames"],
        important: ["utility", "damage"],
        zoning: 0.25,
        rushdown: 0.75,
        oneplayer: "yes",
        range: ["mid", "all"],
        stance: "yes",
        charge: "no",
        gameplan: ["risc", "grab"],
        setplay: ["neutral"],
        projectile: "limited",
        reversal: "metered",
        resource: ["meter","projectile"],
        vortex: "lots",
        score: 0
    },
    pot: {
        name: "Potemkin",
        image: "https://www.dustloop.com/wiki/images/f/f5/GGST_Potemkin_Icon.png",
        playstyle: "rewarding",
        moral_system: "neutral",
        gender: "male",
        favourite: ["pressure"],
        important: ["health", "damage"],
        zoning: 0.5,
        rushdown: 0.5,
        oneplayer: "no",
        range: ["close", "mid"],
        stance: "no",
        charge: "yes",
        gameplan: "grab",
        setplay: "no",
        projectile: "no",
        reversal: "metered",
        resource: "no",
        vortex: "neutral",
        score: 0
    },
    ramlethal: {
        name: "Ramlethal Valentine",
        image: "https://www.dustloop.com/wiki/images/f/fb/GGST_Ramlethal_Valentine_Icon.png",
        playstyle: "rewarding",
        moral_system: "neutral",
        gender: "female",
        favourite: ["combos", "pressure"],
        important: ["all_rounder"],
        zoning: 0.75,
        rushdown: 0.25,
        oneplayer: "no",
        range: ["mid", "long"],
        stance: "no",
        charge: "no",
        gameplan: ["highlow", "risc"],
        setplay: "no",
        projectile: "standard",
        reversal: "metered",
        resource: "ammo",
        vortex: "neutral",
        score: 0
    },
    leo: {
        name: "Leo Whitefang",
        image: "https://www.dustloop.com/wiki/images/6/64/GGST_Leo_Whitefang_Icon.png",
        playstyle: "rewarding",
        moral_system: "good",
        gender: "male",
        favourite: ["pressure", "mindgames"],
        important: ["damage", "health"],
        zoning: 0.0,
        rushdown: 1.0,
        oneplayer: "sometimes",
        range: "close",
        stance: "yes",
        charge: "yes",
        gameplan: ["highlow", "frametrap", "leftright"],
        setplay: "neutral",
        projectile: "standard",
        reversal: ["meterless", "metered"],
        resource: "no",
        vortex: "neutral",
        score: 0
    },
    anji: {
        name: "Anji Mito",
        image: "https://www.dustloop.com/wiki/images/b/b2/GGST_Anji_Mito_Icon.png",
        playstyle: "specialist",
        moral_system: "neutral",
        gender: "male",
        favourite: ["pressure", "neutral"],
        important: ["all_rounder"],
        zoning: 0.25,
        rushdown: 0.75,
        oneplayer: "no",
        range: "mid",
        stance: "yes",
        charge: "no",
        gameplan: ["frametrap"],
        setplay: ["neutral", "oki"],
        projectile: "limited",
        reversal: "metered",
        resource: "no",
        vortex: "projectile",
        score: 0
    },
    nago: {
        name: "Nagoriyuki",
        image: "https://www.dustloop.com/wiki/images/2/2c/GGST_Nagoriyuki_Icon.png",
        playstyle: "specialist",
        moral_system: "evil",
        gender: "male",
        favourite: ["pressure", "combos"],
        important: ["damage", "health"],
        zoning: 0.75,
        rushdown: 0.25,
        oneplayer: "no",
        range: ["mid", "long"],
        stance: "yes",
        charge: "no",
        gameplan: ["frametrap", "risc"],
        setplay: "no",
        projectile: "limited",
        reversal: "metered",
        resource: "meter",
        vortex: "neutral",
        score: 0
    },
    giovanna: {
        name: "Giovanna",
        image: "https://www.dustloop.com/wiki/images/4/41/GGST_Giovanna_Icon.png",
        playstyle: "prepared",
        moral_system: "neutral",
        gender: "female",
        favourite: ["pressure"],
        important: ["mobility", "all_rounder"],
        zoning: 0.0,
        rushdown: 1.0,
        oneplayer: "sometimes",
        range: "close",
        stance: "no",
        charge: "no",
        gameplan: ["frametrap", "risc"],
        setplay: "no",
        projectile: "no",
        reversal: ["meterless", "metered"],
        resource: "no",
        vortex: "neutral",
        score: 0
    }
}

function reset_characters() {
    for (var char in characters) {
        characters[char].score = 0;
    }
}
function check_characters(result) {
    for (var char in characters) {
        if (typeof(characters[char][result.key]) === "number") {
            check_numbers(char, result);
        } else {
            check_strings(char, result);
        }
    }
}

function check_strings(char, result) {
    if (characters[char][result.key].includes(result.id) || result.id === "none") {
        characters[char].score += result.amount;
    }
}

function check_numbers(char, result) {
    characters[char].score += result.amount * characters[char][result.key];
}

function check_winner() {
    var winners = [];
    for (var char in characters) {
        winners.push({score: characters[char].score, name: characters[char].name, image: characters[char].image}); 
    }
    winners.sort((a, b) => b.score - a.score);
    return winners;
}